require("prototypes.efficiency4")
require("prototypes.efficiency5")
require("prototypes.productivity4")
require("prototypes.productivity5")
require("prototypes.speed4")
require("prototypes.speed5")
require("prototypes.quality4")
require("prototypes.quality5")
